spring:
  application:
    name: employee-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_service?currentSchema=employee
    username: employee_service
    password: c2RyMzQ2NTZpNHRycmRx
  data:
    redis:
      host: localhost
      port: 6379
      password: WmwycXU0NG1AUmVkaXNQYXNzd29yZA==

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans